version: "3.8"
services:
  db:
    image: postgres:15
    container_name: retailops_db
    environment:
      POSTGRES_DB: retail
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
